### ISSUE TITLE
Deploy via helm without nginx-ingress

### ISSUE THREAD

**Issue by theluke** [ContainerSolutions/weaveDemo#897]
Hi folks, is it possible to add a feature flag to deploy the app without the `nginx-ingress` pod?

I suggest adding at the top of the [ingress.yaml ](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/helm-chart/templates/ingress.yaml)this line
`{{- if .Values.ingress.enabled }}`

and modifying `values.yaml`

```
ingress:
    enabled: false
    annotations:
        kubernetes.io/ingress.class: nginx
    labels: {}
    host: ''
    tlsSecretName: ''
```
